image: Visual Studio 2022

configuration:
  - Release

environment:
  matrix:
    - arch: x64

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile https://sdk.lunarg.com/sdk/download/1.3.246.0/windows/VulkanSDK-1.3.246.0-Installer.exe -FileName VulkanSDK-Installer.exe
  - VulkanSDK-Installer.exe --accept-licenses --default-answer --confirm-command install
  - set VULKAN_SDK=C:\VulkanSDK\1.3.246.0
  - set VK_SDK_PATH=C:\VulkanSDK\1.3.246.0

cache:
  - VulkanSDK-Installer.exe
  - yuzu\build\vcpkg_installed
  - c:\tools\vcpkg\installed\

before_build:
  - git submodule update --init --recursive
  - cmd: |-
      cd yuzu
      mkdir build
      cd build
      cmake .. -G "Visual Studio 17 2022" -A %arch% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DYUZU_TESTS=no

build_script:
  - cmd: |-
      cd yuzu/build
      cmake --build . --config Release

after_build:
  - 7z a Release.zip yuzu/build/bin/Release

artifacts:
  - path: yuzu/build/bin/Release.zip
    name: Release
